config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   root 'welcome#index'

resources :trainers do
  collection do 
    post :import
    get :search
  end
end
 get "/signup", :to => "welcome#signup"

end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
    validates :profile_type, :industry,:expertise,:geography, :rating,:presence => true
     REFIRENCE = ["yes","no"]
	    mount_uploader :avatar, AvatarUploader

  scope :trainer_profile_type, ->(tprofile_type){where("profile_type = ?", "#{tprofile_type}") if tprofile_type.present?}
  scope :trainer_expertise, ->(texpertise){where("expertise like ?", "#{texpertise}") if texpertise.present?}
  scope :trainer_location, ->(tgeography){where("geography like ?", "#{tgeography}") if tgeography.present?}
  scope :trainer_rating, ->(trating){where("rating = ?", "#{trating}") if trating.present?}


  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
    csv << column_names
      all.each do |trainer|
       csv << trainer.attributes.values_at(*column_names)
      end
    end
  end
  
  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
    row = Hash[[header, spreadsheet.row(i)].transpose]
      trainer = find_by_id(row["id"]) || new
      trainer.attributes = row.to_hash.slice(*accessible_attributes)
      trainer.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Csv.new(file.path, nil, :ignore)
    when ".xls" then Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end


  def self.search(name,expertise,location,rating)
    where("profile_type = ? AND (expertise LIKE ? OR geography LIKE ? OR rating = #{rating})","#{name}", "%#{expertise}%", "%#{location}%") 
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 include ApplicationHelper
  before_action :configure_permitted_parameters, if: :devise_controller?

  def is_login?
    unless current_user
      redirect_to "/"
    end
  end



def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:email,:role, :first_name, :last_name, :username, :gender_type_list, :name, :address, :city, :phone, :date_of_birth,:password, :password_confirmation)
  end
 
def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(User)
    root_path
     end
  end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController

	def index


    @trainer= Trainer.new
    respond_to do |format|
      format.html
      format.csv { send_data @trainers.to_csv }
      format.xls # { send_data @products.to_csv(col_sep: "\t") }
    end
  end

  def search
   @trainers=Trainer.all.order("created_at ASC")
  	if params[:profile_type].blank? and params[:trainer_expertise].blank? and params[:trainer_geography].blank? and params[:rating].blank?
  	  @trainers = []
    else
      @trainers = Trainer.trainer_profile_type(params[:profile_type]).trainer_expertise(params[:trainer_expertise]).trainer_location(params[:trainer_geography]).trainer_rating(params[:rating])
    end

  end

  def import
	  file  = params[:file]
	  book   = Spreadsheet.open(file.path)
    sheet1 = book.worksheet 0
    sheet1.each do |row|    	
      Trainer.create(:name => row[1],:profile_type => row[2],:industry => row[3], :experience => row[4], :expertise => row[5], :geography => row[6], :rating => row[7],:references => row[8])
    end
      redirect_to trainers_url, notice: "Spreadsheet is imported."
  end

  def new
		@trainer= Trainer.new
  end

  def create
		@trainer= Trainer.new(trainer_params)
    if @trainer.save
			redirect_to trainers_path
		else
			render "new"
		end
	end

  def show
		@trainer= Trainer.find(params[:id])
	end

  def edit
		@trainer= Trainer.find(params[:id])
	end

  def update
		@trainer= Trainer.find(params[:id])
		if @trainer.update(trainer_params)
			 redirect_to trainers_path
		else
			render "edit"
		end
	end

  def destroy
		@trainer= Trainer.find(params[:id])
		@trainer.destroy
		redirect_to trainers_path
	end

private

  def trainer_params
		params.require(:trainer).permit!
	end
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@trainer= Trainer.new
  end


  def signup
	@trainers= Trainer.all
   end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<style>
  #footer {
    clear: both;
    height: 90px;
    color:#ccc;
    font-size:12px;
    position:relative;
    z-index: 10;
    margin-top: -3em;
    background-color:black;
    top: 305px;
  }
 
  div.text-center{
    float: center;
  }
  div.text-right{
     float: right;
  }
  div.text{
     margin-left: 75px;
     margin-right: 75px;
     margin-bottom: 10px;
  }

  div.image{
    padding-top: 20px;
    margin-left: 70px;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XLS</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
    <body>

      <nav id ="nav">

        <div id= "page_nav" >
       
         <%= link_to ('Home<span class="glyphicon glyphicon-home"> </span>').html_safe, root_path %>
          <%= link_to "About","#"  %>
    
        </div>
   
        <div id= "sign_in" >
          <% if current_user.present? %>
              <%= link_to ('Trainers<span class="glyphicon glyphicon-user"> </span>').html_safe, trainers_path %>
            <%= link_to ('<span class="glyphicon glyphicon-off"></span>').html_safe, destroy_user_session_path, :method => :delete %>
         <% else %>
            <%= link_to "Help?", root_path %>
        <%= link_to ('Signup <span class="glyphicon glyphicon-pencil"> </span>').html_safe,signup_path  %>
          
            <%= link_to ('Sign in <span class="glyphicon glyphicon-user"> </span>').html_safe, new_user_session_path(current_user)  %>
          <% end %>
          
        </div>

      </nav>
        <div id= "main_wrap" >
  
          <%= form_tag search_trainers_path, :method => 'get', style: "width: 100%; text-align: center; position: relative; top: -44px;",:id => "search" do %>
         <h1 style="position: relative; top: -41px; font-weight: bold; color: white; text-align: center; width: 1089px;"> TRAINERZHUB.COM</h1>
            <h2 style="position: relative;top: 10px;font-weight:bold;color:red;">
              SEARCH FOR TRAINERS & VENDORS &<br> ACROSS SECTORS & EXPERTISE AREAS</h2><br>
               <%= select_tag :profile_type, options_for_select([["Select",""],["Trainer","Individual"],["Vendor","Company"]], selected: params[:profile_type]), :style => "border: 1px solid green;" ,class: "btn btn-primary btn-lg" %> 
                <%#= select_tag :trainer_industry,options_for_select([["Industry",""]]+Trainer.all.map{|a| a.industry}), :style => "border: 1px solid green;" ,class: "btn btn-primary" %>
                <%= select_tag :trainer_expertise, options_for_select([["Expertise",""]]+(Trainer.all.map{|a| a.expertise}).uniq, selected: params[:trainer_expertise]), :style => "border: 1px solid green;" ,class: "btn btn-primary btn-lg" %>
                <%= select_tag :trainer_geography, options_for_select([["Location",""]]+(Trainer.all.map{|a| a.geography}).uniq, selected: params[:trainer_geography]), :style => "border: 1px solid green;" ,class: "btn btn-primary btn-lg" %>
                <%= select_tag :rating, options_for_select([["Rating",""]]+(Trainer.all.map{|a| a.rating}).uniq, selected: params[:rating]), :style => "border: 1px solid green;font_size:40;" ,class: "btn btn-primary btn-lg" %>

                  <%= submit_tag "Search",class: "btn btn-success btn-lg" %>   
              <% end %>
        </div>
    
        <div class="container">
            <%= yield %>
            </div>
              </body> <br><br><br>
          <div class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
              <h7 style="position: relative;top: 16px; left: 560px;font-weight:bold;color:white;"> @ All Rights Reserved</h7>

        </div>
</html>


   
<script>
  $("#search").validate();
</script>
<style>
 div.text-center{
     float: center;

}
</style>

app/views/trainers/_form.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Trainers New</h4>
      </div>
      <div class="modal-body">
   <%= form_for @trainer, html: { multipart: true } do |f| %>
  <% if @trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>
      <ul>
        <% @trainer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
      <%= f.label :name %><br/>
      <div class="input-group">
        <%= f.text_field :name, placeholder: "", class: "form-control input-lg", label: false, :required =>true %>
      </div><br/>

      <%= f.label :type %><br/>
      <div class="input-group">
        <%= f.text_field :profile_type, placeholder: "", class: "form-control input-lg", label: false, :required =>true %>
      </div><br/>

      <%= f.label :industry %><br/>
      <div class="input-group">
       
          <%= f.text_field :industry, placeholder: "", class: "form-control input-lg", label: false, :required =>true %>
      </div><br/>
      <%= f.label :experience %><br/>
      <div class="input-group">
        <%= f.number_field :experience, placeholder: "", class: "form-control input-lg", label: false, :required =>true %>
      </div><br/>

      <%= f.label :Expertise %><br/>
      <div class="input-group">
         
          <%= f.text_field :expertise, placeholder: "", class: "form-control input-lg", label: false, :required =>true %>
      </div><br/>
        <%= f.label :geography %><br/>
      <div class="input-group">
        
          <%= f.text_area :geography, placeholder: "", class: "form-control input-lg", label: false, :required =>true %>
        </div><br/>        


      <%= f.label :rating %><br/>
      <div class="input-group">
       
          <%= f.number_field :rating, placeholder: "rating", class: "form-control input-lg", label: false, :required =>true %>
      </div><br/>
      <div class="field">
      <%= f.label :References %>
      <div class="input-group">
        <%= f.select :references, Trainer::REFIRENCE, prompt: 'yes', class: "form-control input-lg", label: false, :required =>true %>
       </div>
        <%= f.label :File %><br/>
        <%= f.file_field :avatar, :required =>true %>
      </div><br/>

       <%= f.submit "Create trainer" %>
<% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/trainers/edit.html.erb
<h1>Editing Contact</h1>
<%= render 'form' %>
<%= link_to 'Show', @trainer %> 

app/views/trainers/index.html.erb
<link href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
<table id="example" class="table table-striped table-bordered"cellspacing="0" width="100%">

  <thead>
    <tr>
      <th>SN</th>
      <th>Trainer Name</th>
      <th>Type</th>
      <th>Industry</th>
      <th>Years of<br> Experience <br>(years)</th>
      <th>Expertise</th>
      <th>Geography</th>
      <th>Overall<br> Ratings on</th>
      <th>References</th>
      <th>Caption<br>part</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainers.each_with_index do |trainer,index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%=link_to trainer.name,trainer_path(trainer.id) %></td>
        <td><%= trainer.profile_type %></td>
        <td><%= trainer.industry %></td>
        <td><%= trainer.experience %></td>
        <td><%= trainer.expertise %></td>
        <td><%= trainer.geography %></td>
        <td><%= trainer.rating %></td>
        <td><%= trainer.references %></td>
        <%#= link_to "File", trainer.avatar_url %>
        <td><%= link_to ('<span class="glyphicon glyphicon-trash"> </span>').html_safe,  trainer, method: :delete, confirm: "Are you sure that you wish to delete #{trainer.name}?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 Download:
  <td><%= link_to "CSV", trainers_path(format: "csv") %> |
  <%= link_to "Excel", trainers_path(format: "xls") %></td><br>


<h2>Import Spreadsheet</h2>
  <%= form_tag import_trainers_path, multipart: true do %>
    <%= file_field_tag :file %><%= submit_tag "Import" %>
  <% end %><br><br><br>
     
<script src="/assets/jquery.dataTables.min.js" type="text/javascript"></script>

<script>
$(document).ready(function() {
    $('#example').DataTable();
} );
</script>
<!-- Button trigger modal -->

app/views/trainers/index.xls.erb
<div class="col-md-6 col-md-offset-5">
  <div class="panel panel-default">
    <div class="panel-heading">

<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">SN</Data></Cell>
        <Cell><Data ss:Type="String">Trainer Name</Data></Cell>
        <Cell><Data ss:Type="String">Type</Data></Cell>
        <Cell><Data ss:Type="String">Industry</Data></Cell>

           <Cell><Data ss:Type="decimal">Years of Experience (years)</Data></Cell>
        <Cell><Data ss:Type="String">Expertise</Data></Cell>
        <Cell><Data ss:Type="String">Type</Data></Cell>
        <Cell><Data ss:Type="String">Industry</Data></Cell>

           <Cell><Data ss:Type="String">Overall Ratings on</Data></Cell>
        <Cell><Data ss:Type="String">References</Data></Cell>
      </Row>

   <% @trainers.each_with_index do |trainer,index| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= index + 1  %></Data></Cell>
        <Cell><Data ss:Type="String"><%= trainer.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= trainer.profile_type %></Data></Cell>
        <Cell><Data ss:Type="String"><%=trainer.industry%></Data></Cell>

             <Cell><Data ss:Type="Number"><%=trainer.experience  %></Data></Cell>
        <Cell><Data ss:Type="String"><%= trainer.geography %></Data></Cell>
        <Cell><Data ss:Type="String"><%= trainer.rating %></Data></Cell>
        <Cell><Data ss:Type="String"><%=trainer.references%></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>


</div></div></div>

app/views/trainers/new.html.erb
<div class="col-md-8 col-md-offset-0">
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="text-right">
         <h4><%= link_to ('<span class="glyphicon glyphicon-remove"> </span> ' ).html_safe, root_path %></h4>
      </div>
      <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>
        <h1>Trainer</h1>
      <%= render 'form' %>
    </div>
  </div>
</div><br>

app/views/trainers/search.html.erb
       <div class="text-center">
<% if !@trainers.present? %>
       <b><p style="color:red;">No records found!</p></b>
  <%else%>
    <% for trainer in @trainers %>
      <td>
        <strong>Trainer Name:</strong>
        <%= trainer.name %>
      </td><br>
      <td>
        <strong>Trainer Type:</strong>
        <%= trainer.profile_type %>
      </td><br>
      <td>
        <strong>Location:</strong>
         <%= trainer.geography %>
      </td><br>
      <td>
        <strong>Expertise:</strong>
        <%= trainer.expertise %>
      </td><br>
      <td>
       <strong>Rating:</strong>
       <%= trainer.rating %>
      </td><br><br>
    <% end %>
  <% end %>
   <%= link_to "back", root_path %>  
</div> <br><br><br><br>


<style>
   div.text-center{
     float: center;
}
  div.text-right{
     float: right;
}
</style>

app/views/trainers/show.html.erb
<div class="text-center">
  <p>
  <strong>Name:</strong>
  <%= @trainer.name %>
  </p>
  <p>
  <strong>Location:</strong>
  <%= @trainer.geography %>
  </p>
  <p>
  <strong>Experience:</strong>
  <%= @trainer.experience %>
  </p>
  <p>
  <strong>Rating:</strong>
  <%= @trainer.rating %>
  </p>
  <td><%= link_to "Back", trainers_path %></td>
</div>
  <style>
   div.text-center{
     float: center;
    } 
  </style>

app/views/welcome/signup.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
  <h1 style=" color: black;
    font-weight: bold;
    left: -258px;
    position: relative;
    text-align: center;
    top: 3px;
    width: 1089px;"> Create your  account</h1>
    <div class="panel-heading">

<div class="text-center">
 <div id="main-container" class="container-fluid">
      <div class="row">
        <div id="sidebar" class="col-xs-3" style="background: none repeat scroll 0 0 ; height: 11em; left: 70px; top: -3px; width: 38%;border: 1px solid green;" >
       <%= link_to image_tag("trainer.png", alt: "File Name Fancy", size: "70x83"),new_user_registration_path(:role => 'trainer') %>
        <p style="  color: green; font-weight: bold;left: 54px;position: relative;
    text-align: center;
    top: 20px;
    width: 10px"> 
     <%= link_to "Trainers",new_user_registration_path(:role => 'trainer') %></p>
        </div>
        <div id="main-content" class="col-xs-9" style="background: none repeat scroll 0 0 ;
    height: 11em;
    left: 92px;
    top: -3px;
    width: 38%;border: 1px solid green;">
         <%= link_to image_tag("users.png", alt: "File Name Fancy", size: "66x89"), new_user_registration_path(:role => 'user') %>
        <p style="  color: green;
    font-weight: bold;
    left: 54px;
    position: relative;
    text-align: center;
    top: 12px;
    width: 10px"> 
      <%= link_to "Users",new_user_registration_path(:role => 'user') %></p>
        </div>
      </div>
    </div>
   
<br>



</div></div></div></div>

<style type="text/css">  
div.text-center{
    float: center;
  }
  div.text-right{
     float: right;
  }
  </style>